export const FOOD_TYPES: string[] = [
  'american',
  'bagel',
  'bar',
  'bar grill',
  'burger',
  'chinese',
  'cocktail bar',
  'coffee',
  'dessert',
  'filipino',
  'french',
  'german',
  'indian',
  'italian',
  'japanese',
  'juice',
  'korean',
  'mediterranean',
  'mexican',
  'pizza',
  'southern comfort',
  'spanish',
  'thai',
  'tapas',
  'taqueria',
  'ukrainian',
  'vietnamese',
]

export const NEIGHBORHOODS: string[] = [
  'Harlem',
  'MorningSide',
  'UWS',
  'UES',
  'Midtown',
  'Ktown',
  'Flatiron',
  'Chelsea',
  'East Village',
  'West Village',
  'Washington Square Park',
  'Lower Manhattan',
  'LES',
  'FiDi',
  'Flushing',
  'Astoria',
  'LIC',
  'Greenpoint',
  'Williamsburg',
  'Bushwick',
  'Park Slope',
  'Prospect Heights',
  'Downtown Brooklyn',
  'DUMBO',
]

export const RATING: number[] = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]

export const ADVANCED: string[] = ['subcategory', 'permanantelyClosed']
